AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Global API - API Gateway account.

Parameters:
  Versao:
    Type: String
    Default: 1
  Env:
    Description: Execution environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  ServiceName:
    Description: Service Name
    Type: String
    Default: service-name
  PlatformName:
    Description: Platform Name (TAG)
    Type: String
    Default: plataform-name
  ProductName:
    Description: Product Name (TAG)
    Type: String
    Default: product-name
  ComponentName:
    Description: Component Name (TAG)
    Type: String
    Default: component-name
  ScopeName:
    Description: Scope Type (pci,pci-conneted,non-pci)
    Type: String
    Default: non-pci
    AllowedValues:
      - pci
      - pci-connected
      - non-pci
  SquadName:
    Description: Squad Name (TAG)
    Type: String
    Default: squad-name

Conditions:
  IsPrd: !Equals 
    - !Ref Env
    - prd

Mappings:
  Throttle:
    DefaultRate:
      value: 1000
    DefaultBurst:
      value: 1000

Resources:
  ApiGwAccountConfig:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
        - ApiGatewayLoggingRole
        - Arn
  ApiGatewayLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
  GlobalAPIUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: GlobalAPIUsagePlan
      Description: UsagePlan to configuration Throttle in ApiGateway.
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}         
        - Key: name
          Value: !Ref ServiceName
        - Key: platform
          Value: !Ref  PlatformName
        - Key: product
          Value: !Ref ProductName
        - Key: component
          Value: !Ref ComponentName
        - Key: scope
          Value: !Ref ScopeName
        - Key: squad
          Value: !Ref SquadName
        - Key: resource
          Value: usage-plan
      Throttle:
        BurstLimit:
          Fn::FindInMap:
          - Throttle
          - DefaultRate
          - value
        RateLimit:
          Fn::FindInMap:
          - Throttle
          - DefaultBurst
          - value