AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Secret Manager

Parameters:
  Versao:
    Type: String
    Default: 1.0
  Env:
    Description: Execution environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - hml
      - prd
  SecretName:
    Description: Secret Name
    Type: String
    Default: secret-name

  PlatformName:
    Description: Platform Name (TAG)
    Type: String
    Default: plataform-name
  ProductName:
    Description: Product Name (TAG)
    Type: String
    Default: product-name
  ComponentName:
    Description: Component Name (TAG)
    Type: String
    Default: component-name
  ScopeName:
    Description: Scope Type (pci,pci-conneted,non-pci)
    Type: String
    Default: non-pci
    AllowedValues:
      - pci
      - pci-connected
      - non-pci
  SquadName:
    Description: Squad Name (TAG)
    Type: String
    Default: squad-name

Conditions:
  IsPrd: !Equals 
    - !Ref Env
    - prd

Resources:
  AccessKeyIDSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Ref SecretName
      Description: "Secret Access Key ID"
      SecretString: '{"access_key_id": "abcdev", "secret_access_key": "qwerty"}'
      Tags:
      Tags:
        - Key: env
          Value: !Ref Env
        - Key: stack
          Value: !Sub ${AWS::StackName}         
        - Key: name
          Value: !Ref SecretName
        - Key: platform
          Value: !Ref  PlatformName
        - Key: product
          Value: !Ref ProductName
        - Key: component
          Value: !Ref ComponentName
        - Key: scope
          Value: !Ref ScopeName
        - Key: squad
          Value: !Ref SquadName
        - Key: resource
          Value: usage-plan